#!/usr/bin/env bash
sudo apt update && sudo apt upgrade
sudo apt-get install -y curl git software-properties-common 
sudo apt-add-repository --yes --update ppa:ansible/ansible
sudo apt install ansible -y
