# LATEST

- name: install dependencies
  become: true
  apt: name=software-properties-common
  tags: 
    - install
    - dependencies

- name: add-apt-repository 
  become: true
  apt_repository:
    repo: ppa:neovim-ppa/unstable
    update_cache: True
  tags:
    - update
    - add-apt-repository

- name: install neovim
  become: true
  apt: name=neovim
  tags:
    - install



